### ISSUE TITLE
If input quickly editor does some loops with chars (in controlled mode)

### ISSUE THREAD

**Issue by Janekk** [zenoamaro/react-quill#10]
When using `react-quill` component in *controlled* mode (roundtrip with `onChange` event and passing back the value through `props`) and input quickly it will fall into an infinite loop constantly updating editor states (e.g.: `<div>abcd</div>` updated to `<div>abcde</div>` back and forth)

```
<ReactQuill value={project.description}
  theme="snow" onChange={this.onEditorChange.bind(this, 'description')} />
````

If the *uncontrolled* mode is used (`defaultValue` instead of `value`) the problem goes away.

**Comment by whatSocks** [comment]
Yes, I am getting this issue as well.

**Comment by zenoamaro** [comment]
I should have a bit of time this week to debug this issue.

**Comment by zenoamaro** [comment]
@Janekk, I cannot seem to reproduce the issue right now.

I know the issue exists, because it had also happened to me some time ago.

Can you put a test case on [jsbin](jsbin.com) or similar? I have also updated the demo in the package with two-way binding for both the editor and a textarea to test the issue. Do you see any difference?

**Comment by zenoamaro** [comment]
This should fix this issue. I was never able to reproduce it personally, so please re-open this issue if you see that this hasn't been solved yet.
