### ISSUE TITLE
Change toolbar default  items values

### ISSUE THREAD

**Issue by friendOfOurs** [zenoamaro/react-quill#148]
Hi,

In the previous version you could set the value for toolbar item with: 
`<ReactQuill  toolbar={this.toolbarItems}>`
and this.toolbarItems would then have array of labels and values for formats, e.g. size.

Can this be achieved with modules and formats props? 
Cheers!

**Comment by zenoamaro** [comment]
Yes, you can still do the same. In fact React Quill will print how to do it in the console.

If you were using the new Quill format already, you can do `<ReactQuill modules={{toolbar: toolbarItems}}/>` instead. You can recognize this format because it's composed of only arrays and strings.

If you were using the React Quill Toolbar format, instead, you will have to create a `Quill.Toolbar` yourself now, and pass the ID to React Quill. You can recognize this format because it has arrays of objects with the `type` property. React Quill will also warn you if this is the case.

See https://github.com/zenoamaro/react-quill/blob/f5717cd50b1371359c64fc74a789700d8e9e46a7/README.md#upgrading-to-react-quill-v1-0-0
