### ISSUE TITLE
[1.0.0-beta-1] React warning when unmouting React-Quill while some text is selected

### ISSUE THREAD

**Issue by jrmmnr** [zenoamaro/react-quill#153]
This is only visible when `NODE_ENV !== 'production'`.

Warning in console :  

> Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Quill component.
> printWarning @ warning.js?8a56:36
> warning @ warning.js?8a56:60
> getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js?6531:48
> enqueueSetState @ ReactUpdateQueue.js?6531:200
> ReactComponent.setState @ ReactComponent.js?702a:63
> onEditorChangeSelection @ component.js?a7f0:261
> (anonymous) @ mixin.js?ac20:38
> emit @ quill.js?0ef8:5313
> emit @ quill.js?0ef8:5135
> update @ quill.js?0ef8:6206

A possible solution (not sure it is the best) is to update src/component.js :
```
componentWillUnmount: function() {
	// NOTE: Don't set the state to null here
	//       as it would generate a loop.

	var e = this.getEditor();
	if (e) {
		e.off('editor-change');
		e.off('selection-change');
	}
},
```

Tested only with React 15.4.2 and React-Quill 1.0.0-beta-1

Codepen http://codepen.io/anon/pen/BpgGNL?editors=0010#0

**Comment by ariona** [comment]
@alexkrolick Just got this warning, what should i do? wait for the update? 😄

**Comment by alexkrolick** [comment]
Yes, will push beta 2 soon. Thanks for waiting.

On Tue, Feb 21, 2017, 8:17 AM Rian Ariona <notifications@github.com> wrote:

@alexkrolick <https://github.com/alexkrolick> Just got this warning, what
should i do? wait for the update? 😄

—
You are receiving this because you were mentioned.


Reply to this email directly, view it on GitHub
<https://github.com/zenoamaro/react-quill/issues/153#issuecomment-281392612>,
or mute the thread
