### ISSUE TITLE
Removing formatting on paste

### ISSUE THREAD

**Issue by jordancalder** [zenoamaro/react-quill#220]
From the quill documentation, the removeFormat method should be available from version 1.0.0, but I've been unable to implement that functionality here. Id like to remove formatting when text is pasted.

**Comment by alexkrolick** [comment]
Thanks for the report, can you add a few things?

- What version are you using?
- Are you using the ReactQuill ref to get the editor instance? https://github.com/zenoamaro/react-quill#methods
- What error are you seeing, if any?

**Comment by alexkrolick** [comment]
Consolidating discussion of this and #222 here.

The most reliable way to override paste functionality is to use the Quill [clipboard module ](https://quilljs.com/docs/modules/clipboard/#clipboard%20module) and turn all the matchers (`B`, `P`, etc.) into plain text nodes when they are transformed into Quill deltas. _This will almost certainly have side-effects if you use ReactQuill as a controlled component_ (using `value` instead of `defaultValue`) as the component uses `dangerouslyPasteHTML` internally to synchronize the editor contents with the `value` prop. Uncontrolled mode is probably fine for most use cases, however - you can still listen use the `onChange` callback to set the state of an external store, for example.

**Comment by quangphat** [comment]
`var x = 3;`
