### ISSUE TITLE
issue for custom buttons using State values

### ISSUE THREAD

**Issue by tylerkrett** [zenoamaro/react-quill#275]
Hey Guys,

I am currently trying to make a color picker for react quill, but having a few issues on the way.

Firstly I have a color picker that saves the hexadecimal value to state.

but in my buttons function it will not allow me to use this.state.color because it is not defined due to the this.quill methods.

I passed it in as a parameter but then the this on that function is broken and errors occur.

The given range isn't in document.
uncaught TypeError: Cannot read property 'innerHTML' of null.

Any suggestions how to get this working ?

**Comment by alexkrolick** [comment]
It would help if you could provide a Codepen link demonstrating the troubles you are having:

- Default template: https://codepen.io/pen?template=xgyOXQ
- Custom toolbar template: https://codepen.io/pen?template=gmroPj

If you're having trouble with`this` in Javascript and function binding in React you might want to check out this resource: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this

Closing since there is no bug/feature request but discussion can continue.
