### ISSUE TITLE
show html bug not working with css and class render to html

### ISSUE THREAD

**Issue by tinhlv** [zenoamaro/react-quill#288]
show html bug not working with css and class render to html. 
Please help me solve the problem. Thanks Admin !

**Comment by alexkrolick** [comment]
Can you provide more information? What is the error you are seeing?

**Comment by Halsys** [comment]
"I think" I get the issue here... I was able to use [isomorphic-style-loader](https://github.com/kriasoft/isomorphic-style-loader) and [webpack](https://github.com/webpack/webpack) to get the exported html to have some style. Might be useful to someone. Feels like a hack though. Just make your own style classes for your site and you are good to go. Have a nice day! ;)

```javascript

import React from "react";
import RichTextStyle from "./RichTextStyle.css";
import withStyles from "isomorphic-style-loader/lib/withStyles";

class RichTextContainer extends React.Component {
  constructor(props, context) {
    super(...arguments);
  }

  render() {
    let html = {
      __html: this.props.html.replace(
        /class\s?=\s?\"(ql-.*)\"/g,
        (sub, style) => {
          let rep = RichTextStyle[style] || null;
					if(rep) {
						return `class=\"${rep}\"`;
					}
          return sub;
        }
      )
    };
    return <div dangerouslySetInnerHTML={html} />;
  }
}

export default withStyles(RichTextStyle)(RichTextContainer);
```
