### ISSUE TITLE
Question: h2 tag after empty row

### ISSUE THREAD

**Issue by lukezavrel** [zenoamaro/react-quill#333]
Hi, is this a bug, or is the behaviour correct?

https://codepen.io/anon/pen/zRaEYE

When h2 tag is used after empty row, React-Quill adds more empty rows, see codepen example.
I found out that when `clipboard: {
    matchVisual: false,
  }` is used then it works, but the documentation for matchVisual says:
>## matchVisual
>Quill by default does not have padding or margin for each line, whereas some websites or sources where a paste will come from will. By default Quill will try to match this spacing visually by adding an extra line to compensate for the missing margin/padding. This option disables this behavior.

which does not really specify this behaviour.
I used the matchVisual property in my use case, but i don't think it should be necessary.
Please check, thanks

**Comment by alexkrolick** [comment]
`matchVisual: false` makes sense when you trust that the HTML you are starting with looks correct in Quill already. Since the only restore-from-HTML API for Quill is the clipboard API, the fact that the default is `true` can cause some issues as it assumes the input is copied from another editor like Microsoft Word or a website with different styling and tries to compensate.
