### ISSUE TITLE
react-quill crashes app during production build

### ISSUE THREAD

**Issue by sophyphreak** [zenoamaro/react-quill#346]
Development build and webpack-dev-server
![screenshot from 2018-03-28 01-49-58](https://user-images.githubusercontent.com/22810755/37988168-6c999604-322a-11e8-9ec8-e2ae329023df.png)

Production build (including on heroku)
`TypeError: t.isBuffer is not a function`
![screenshot from 2018-03-28 01-52-32](https://user-images.githubusercontent.com/22810755/37988276-b3e641ba-322a-11e8-9945-3251770bdab7.png)

I'm assuming the problem is with my code and not with react-quill, but I don't know where to start debugging this.

Let me know if you want to see other files (such as the webpack.config file). Any thoughts welcome!

#### React-Quill version 
- [X] 1.2.6

**Comment by jasonlow90** [comment]
Hi,

I was facing the same issue yesterday as well and I've managed to fix the problem by following the advices from the quill.js issue section [https://github.com/quilljs/quill/issues/2018](url) and also installing an updated version of uglify [https://github.com/webpack-contrib/uglifyjs-webpack-plugin](url)

Version I am using:
`
"react": "^16.2.0",
"webpack": "^3.11.0",
"react-quill": "^1.2.6",
`

Instead of my old webpack.config.js which doesn't work:

`
module.exports = {
  plugins: [
       new webpack.optimize.UglifyJsPlugin({sourceMap: true}),
  ]
}
`

I npm installed uglifyjs-webpack-plugin with: 

`npm i -D uglifyjs-webpack-plugin` 

And my changed my webpack.config.js  to:

`
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
`
`
module.exports = {
  plugins: [
        new UglifyJsPlugin({sourceMap: true}),
  ]
}
`

I hope this helps you.

Cheers

**Comment by sophyphreak** [comment]
Hey Jason,

It worked! Thanks so much for your help!!

--Andrew

**Comment by paullaros** [comment]
https://github.com/zenoamaro/react-quill#bundling-with-webpack

**Comment by 42x42x42** [comment]
for me it worked as combination of answer above, but with package downgrade: _npm i -D uglifyjs-webpack-plugin**@^1.0.0**_
and plus this  
module: {
        noParse : '/node_modules\\/quill\\/dist/'
}
