### ISSUE TITLE
Can't pass in custom toolbar

### ISSUE THREAD

**Issue by mlennon3** [zenoamaro/react-quill#41]
I'm trying to wrap react-quill in my own components, and use a custom toolbar via the `toolbar` prop to ReactQuill.  There are some issues that combine to prevent me from doing so.

When my component does setState, ReactQuill's shouldComponentUpdate gets called. The equality [on this line](https://github.com/zenoamaro/react-quill/blob/00a0fb0733ba7173915286bd78d6cd6704cc8913/src/component.js#L137) however will return true on the toolbar prop, causing ReactQuill to update when it should not.

When it is doing this update, the component's state fails to include an `editor` property.  Therefore when it rerenders, `destroyEditor` fails, it can't call .destroy of undefined.

Any thoughts on this?

**Comment by zenoamaro** [comment]
Mmh, I'm not able to reproduce this. 

Can you check if #44 solved your issue? Otherwise, are you able to share a minimal program that presents the issue?

By the way, as you saw there is no shallow comparison of object props. I may implement something like that in the future, so please open a separate issue about it if this is important to you.

Still, the correct thing to do would be to keep a static instance of the the object your are passing as the `toolbar` prop around, and keep passing the same unless it changes. This should sidestep your issue completely – unless you're passing other anonymous objects as props, that is.

**Comment by zenoamaro** [comment]
Closed for inactivity. 

Note that with the latest release, the format of the toolbar changed radically. See [Upgrading to React-Quill v1.0.0](https://github.com/zenoamaro/react-quill/blob/f5717cd50b1371359c64fc74a789700d8e9e46a7/README.md#upgrading-to-react-quill-v1-0-0) for further information.
