### ISSUE TITLE
Unable to use span and div tag in react-quill #HELPPLEASE

### ISSUE THREAD

**Issue by slgauravsharma** [zenoamaro/react-quill#446]
Root level is p tag is create all time.
i tried many way but not working
i want to use span and div tag also, when i am passing value as
 `<span>hello<span>world</span></span>`  its convert to `<p>helloworld</p>`.
but my expected should be  `<span>hello<span>world</span></span>` same as what we passing as input.
#HelpPlease #ReactQuill
![issuetag](https://user-images.githubusercontent.com/25609444/50838220-84226180-1383-11e9-8443-e09b87903931.png)

**Comment by kylebeede** [comment]
> i want to use span and div tag also

You can change the default Block tag name like this:
```
var Block = Quill.import('blots/block');
Block.tagName = 'DIV';
Quill.register(Block, true);
```

> when i am passing value as
`<span>hello<span>world</span></span>` its convert to `<p>helloworld</p>`

This is a limitation of Quill. Because `<span>hello<span>world</span></span>` and `<p>helloworld</p>` represent the same content it is part of Quill’s optimization process to unwrap the `<span>`.
