### ISSUE TITLE
Change value prop not works

### ISSUE THREAD

**Issue by gleidsonh** [zenoamaro/react-quill#617]
```js
const [text, setText] = useState('')

const onTextChange = (textTyped) => {
    textTyped = (textTyped.split(' ').length > 3) ? `${textTyped.split(' ').splice(0, 3).join(' ')}</p>` : textTyped
    console.log('textTyped', textTyped)
    setText(textTyped)
}

<ReactQuill
    theme="snow"
    value={text}
    onChange={onTextChange}
    modules={reactQuillModules}
    formats={reactQuillFormats}
    className="mb-4"
/>
```
How you can see here (https://i.imgur.com/wFkYMDB.png), above React Quill state text is working fine (it was cut to 3 words), but value prop it's not updated.

_Originally posted by @gleidsonh in https://github.com/zenoamaro/react-quill/issues/588#issuecomment-643687425_

**Comment by zenoamaro** [comment]
Hello there.

I have played with the reproduction – the issue here is that calling `setText` with the same value it has at that moment does not trigger a prop update. This is the behavior of the `setState` hook.

Until Quill offers a way to prevent edits (as explained in the README), unfortunately there's not much that can be fixed on ReactQuill's side.

However, you can easily modify your example, like this, which will work because a new object doesn't `===` the previous one, even if the contents are the same:

~~~ts
export default function App() {
  const [text, setText] = useState({value: ''}) // Store object instead of string

  const onTextChange = (textTyped) => {
    textTyped = (textTyped.split(' ').length > 3) ? `${textTyped.split(' ').splice(0, 3).join(' ')}</p>` : textTyped
    console.log('textTyped', textTyped)
    setText({value: textTyped})
  }

  return <ReactQuill
    theme="snow"
    value={text.value}
    onChange={onTextChange}
  />
}
~~~

**Comment by avinashk2946** [comment]
This issue still exists; not able to bind data into text editor by passing data using value or default value props.

Note: The assigned value is HTML string

Version : 2.0.0-beta.2

**Comment by codingwesley** [comment]
upgrade version to `react-quill@2.0.0-beta.2 `, and work。

``yarn add react-quill@beta``

**Comment by im5ushant** [comment]
This issue is still not resolved, I am not able to update text-editor's value on state updates

**Comment by se030** [comment]
I had a same issue in `^2.0.0-beta.4` and it works well putting onChange handler in the arrow function notation.
No idea what can cause this difference though

```Typescript
const [ edit, setEdit ] = useState("");
<ReactQuill value={edit} onChange={setEdit} />
```
