### ISSUE TITLE
Selection lost on focus lost

### ISSUE THREAD

**Issue by stanonyime** [zenoamaro/react-quill#62]
This project is great. However, I'm experiencing a loss of my selections on selected text editor whenever I move my mouse to the toolbar.
Basically,
1. I select some text in the editor area.
2. I click the Bold icon to make them bold
3. Nothing happens since my selection is lost
4. I continue typing and all subsequent text will appear bold

Tested on Chrome 47.0.2526.80 m

**Comment by jasonslyvia** [comment]
Experiencing this issue on Chrome 51, Windows 7 too. However on macOS it works fine. It's weird.

**Comment by shatle** [comment]
the same

**Comment by zenoamaro** [comment]
This should be fixed in the latest `master`. Can you verify?

**Comment by jasonslyvia** [comment]
@zenoamaro care to link a specific commit that solves this issue?

**Comment by zenoamaro** [comment]
Commits 7f58c2033e31a09739d2620505a7e218aff54588 and https://github.com/zenoamaro/react-quill/commit/6147f030dbdcaa8707bf2717d904216b7ee07b6c fix lots of similar cases. 

Otherwise just leave a note here and I will try to debug this issue.

Also: try migrating to the standard Quill toolbar. See [Upgrading to React-Quill v1.0.0](https://github.com/zenoamaro/react-quill/blob/f5717cd50b1371359c64fc74a789700d8e9e46a7/README.md#upgrading-to-react-quill-v1-0-0) for more info.

**Comment by alexkrolick** [comment]
It's working on MacOS as reported.

![kapture 2017-02-25 at 18 12 26](https://cloud.githubusercontent.com/assets/1571667/23336461/25a62a72-fb86-11e6-9e2d-a861df584042.gif)

If someone has a Windows machine and wants to do the same test, pull master, `make build` and open `demo/index.html`.
