### ISSUE TITLE
Multiple custom toolbars not displaying correctly

### ISSUE THREAD

**Issue by silverware13** [zenoamaro/react-quill#681]
When using two or more custom toolbars, only the first one on the page is displaying correctly.

This Codepen is the same as the "Custom Toolbar Example". The only difference is that I am creating two separate editors:
https://codepen.io/silverware13/pen/ExgLOKw

**Comment by jvnlwn** [comment]
The issue is due to using the same query selector for the toolbar (`"#toolbar"`). The toolbar query selector must be unique per quill editor instance.

I have run into this issue recently and my current solution is to generate a random ID when the container component mounts and passing that ID to my custom toolbar component and using it as the container in the toolbar module that I pass to the ReactQuill.

This is not a "react way" of handling things. Ideally you could assign a ref to your custom toolbar and pass that node to the quill editor.

With unique toolbar query selectors:
https://codepen.io/joe-vanleeuwen/pen/XWgXedq

<img width="668" alt="Screen Shot 2021-08-30 at 3 39 50 PM" src="https://user-images.githubusercontent.com/5227102/131395409-86454cff-0f5b-4015-b000-cec88c7fc97d.png">

**Comment by jvnlwn** [comment]
@th-e0 the workaround I mentioned did work with functional components. Though, since then, I noticed some issue with that solution that I can't recall now.

My current workaround is to set the ref of the toolbar in state and only once it exists, then render the Quill editor. Here's a simple example:

```javascript
const QuillEditor = (props) => {
  const [toolbarNode, setToolbarNode] = useState()

  const modules = React.useMemo(() => {
    const config = {
      /* ... */
      toolbar: {
        /* ... */
        container: toolbarNode,
      },
    }

    return config
  }, [toolbarNode])

  return (
    <React.Fragment>
      <CustomToolbar
        /* ... */
        ref={setToolbarNode}
      />
      {!!toolbarNode && <ReactQuill /* ... */ modules={modules} />}
    </React.Fragment>
  )
}

```

**Comment by nesh325** [comment]
> @th-e0 the workaround I mentioned did work with functional components.
> 
> My current workaround is to set the ref of the toolbar in state and only once it exists, then render the Quill editor. Here's a simple example:
> 
> ```js
> const QuillEditor = (props) => {
>   const [toolbarNode, setToolbarNode] = useState()
> 
>   const modules = React.useMemo(() => {
>     const config = {
>       /* ... */
>       toolbar: {
>         /* ... */
>         container: toolbarNode,
>       },
>     }
> 
>     return config
>   }, [toolbarNode])
> 
>   return (
>     <React.Fragment>
>       <CustomToolbar
>         /* ... */
>         ref={setToolbarNode}
>       />
>       {!!toolbarNode && <ReactQuill /* ... */ modules={modules} />}
>     </React.Fragment>
>   )
> }
> ```

You mentioned in the past you've tried React.Portal but Quill loses the connection. Have you found a work around for this? Trying to portal this into another component but getting the same issue

**Comment by jvnlwn** [comment]
@nesh325 actually moving to using a toolbar ref instead of a dynamic toolbar ID resolved that issue for me. Have you tried using a ref?

**Comment by jvnlwn** [comment]
@braveheart84 yeah, I'm just forwarding the ref. Here's a more complete example:

```javascript
const CustomToolbar = React.forwardRef(
  (props, ref) => {
    return (
      <div ref={ref}>
        {/* custom toolbar code */}
      </div>
    )
  }
)

const QuillEditor = (props) => {
  const [toolbarNode, setToolbarNode] = useState()

  const modules = React.useMemo(() => {
    const config = {
      /* ... */
      toolbar: {
        /* ... */
        container: toolbarNode,
      },
    }

    return config
  }, [toolbarNode])

  return (
    <React.Fragment>
      <CustomToolbar
        /* ... */
        ref={setToolbarNode}
      />
      {!!toolbarNode && <ReactQuill /* ... */ modules={modules} />}
    </React.Fragment>
  )
}
```

**Comment by araujo2012** [comment]
> @braveheart84 yeah, I'm just forwarding the ref. Here's a more complete example:
> 
> ```js
> const CustomToolbar = React.forwardRef(
>   (props, ref) => {
>     return (
>       <div ref={ref}>
>         {/* custom toolbar code */}
>       </div>
>     )
>   }
> )
> 
> const QuillEditor = (props) => {
>   const [toolbarNode, setToolbarNode] = useState()
> 
>   const modules = React.useMemo(() => {
>     const config = {
>       /* ... */
>       toolbar: {
>         /* ... */
>         container: toolbarNode,
>       },
>     }
> 
>     return config
>   }, [toolbarNode])
> 
>   return (
>     <React.Fragment>
>       <CustomToolbar
>         /* ... */
>         ref={setToolbarNode}
>       />
>       {!!toolbarNode && <ReactQuill /* ... */ modules={modules} />}
>     </React.Fragment>
>   )
> }
> ```

Had the same issue, followed your exemple and it worked! tanks!
